stages:
  - build
  - deploy

build:
  stage: build
  image: maven:latest
  script:
    - mvn clean package

deploy:
  stage: deploy
  image: ruby:latest
  script:
    - apt update -qy
    - apt install -y ruby-dev
    - gem install dpl
    - dpl --provider=heroku --app=<appName> --api-key=$HEROKU_API_KEY