image: maven:latest
stages:
  - build
  - deploy

build:
  stage: build
  script:
    - mvn clean package

deploy:
  stage: deploy
  image: maven:latest
  script:
    - apt update -qy
    - apt install -y ruby-dev
    - gem install dpl
    - dpl --provider=heroku --app=tts-application --api-key=f0194e82-74c8-4a7b-b941-b787c54b0a79