image: openjdk:17

stages:
  - deploy

deploy:
  stage: deploy
  script:
    - apt-get update -qy
    - apt-get install -y wget
    - wget -qO- https://toolbelt.heroku.com/install-ubuntu.sh | sh
    - apt-get install -y ruby
    - gem install dpl
    - dpl --provider=heroku --app=tts-application --api-key=$HEROKU_API_KEY