INSERT INTO language(name)
VALUES ('Afrikaans (South Africa)'),
       ( 'Amharic (Ethiopia)'),
       ( 'Arabic (United Arab Emirates)'),
       ( 'Arabic (Bahrain)'),
       ( 'Arabic (Algeria'),
       ( 'Arabic (Egypt)'),
       ( 'Arabic (Iraq)'),
       ( 'Arabic (Jordan)'),
       ( 'Arabic (Kuwait)'),
       ( 'Arabic (Lebanon)'),
       ( 'Arabic (Libya)'),
       ( 'Arabic (Morocco)'),
       ( 'Arabic (Oman)'),
       ( 'Arabic (Qatar)'),
       ( 'Arabic (Saudi Arabia)'),
       ( 'Arabic (Syria)'),
       ( 'Arabic (Tunisia)'),
       ( 'Arabic (Yemen)'),
       ( 'Azerbaijani (Azerbaijan)'),
       ( 'Bulgarian (Bulgaria)'),
       ( 'Bengali (India)'),
       ( 'Bosnian (Bosnia)'),
       ( 'Catalan (Spain)'),
       ( 'Czech (Czech)'),
       ( 'Welsh (United Kingdom)'),
       ( 'Danish (Denmark)'),
       ( 'German (Austria)'),
       ( 'German (Switzerland)'),
       ( 'German (Germany)'),
       ( 'Greek (Greece)'),
       ( 'English (Australia)'),
       ( 'English (Canada)'),
       ( 'English (United Kingdom)'),
       ( 'English (Hongkong)'),
       ( 'English (Ireland)'),
       ( 'English (India)'),
       ( 'English (Kenya)'),
       ( 'English (Nigeria)'),
       ( 'English (New Zealand)'),
       ( 'English (Philippines)'),
       ( 'English (Singapore)'),
       ( 'English (Tanzania)'),
       ( 'English (United States)'),
       ( 'English (South Africa)'),
       ( 'Spanish (Argentina)'),
       ( 'Spanish (Bolivia)'),
       ( 'Spanish (Chile)'),
       ( 'Spanish (Colombia)'),
       ( 'Spanish (Costa Rica)'),
       ( 'Spanish (Cuba)'),
       ( 'Spanish (Dominican Republic)'),
       ( 'Spanish (Ecuador)'),
       ( 'Spanish (Spain)'),
       ( 'Spanish (Equatorial Guinea)'),
       ( 'Spanish (Guatemala)'),
       ( 'Spanish (Honduras)'),
       ( 'Spanish (Mexico)'),
       ( 'Spanish (Nicaragua)'),
       ( 'Spanish (Panama)'),
       ( 'Spanish (Peru)'),
       ( 'Spanish (Puerto Rico)'),
       ( 'Spanish (Paraguay)'),
       ( 'Spanish (El Salvador)'),
       ( 'Spanish (United States)'),
       ( 'Spanish (Uruguay)'),
       ( 'Spanish (Venezuela)'),
       ( 'Estonian (Estonia)'),
       ( 'Persian (Iran)'),
       ( 'Finnish (Finland)'),
       ( 'Filipino (Philippines)'),
       ( 'French (Belgium)'),
       ( 'French (Canada)'),
       ( 'French (Switzerland)'),
       ( 'French (France)'),
       ( 'Irish (Ireland)'),
       ( 'Galician'),
       ( 'Gujarati (India)'),
       ( 'Hebrew (Israel)'),
       ( 'Hindi (India)'),
       ( 'Croatian (Croatia)'),
       ( 'Hungarian (Hungary)'),
       ( 'Indonesian (Indonesia)'),
       ( 'Icelandic (Iceland)'),
       ( 'Italian (Italy)'),
       ( 'Japanese (Japan)'),
       ( 'Javanese (Indonesia)'),
       ( 'Georgian (Georgia)'),
       ( 'Kazakh (Kazakhstan)'),
       ( 'Khmer (Cambodia)'),
       ( 'Kannada (India)'),
       ( 'Korean (Korea)'),
       ( 'Lao (Laos)'),
       ( 'Lithuanian (Lithuania)'),
       ( 'Latvian (Latvia)'),
       ( 'Macedonian (Republic of North Macedonia)'),
       ( 'Mongolian (Mongolia)'),
       ( 'Marathi (India)'),
       ( 'Malay (Malaysia)'),
       ( 'Maltese (Malta)'),
       ( 'Burmese (Myanmar)'),
       ( 'Norwegian (Bokmål, Norway)'),
       ( 'Nepali (Nepal)'),
       ( 'Dutch (Belgium)'),
       ( 'Dutch (Netherlands)'),
       ( 'Polish (Poland)'),
       ( 'Pashto (Afghanistan)'),
       ( 'Portuguese (Brazil)'),
       ( 'Portuguese (Portugal)'),
       ( 'Romanian (Romania)'),
       ( 'Russian (Russia)'),
       ( 'Sinhala (Sri Lanka)'),
       ( 'Slovak (Slovakia)'),
       ( 'Slovenian (Slovenia)'),
       ( 'Somali (Somalia)'),
       ( 'Albanian (Albania)'),
       ( 'Serbian (Serbia)'),
       ( 'Swedish (Sweden)'),
       ( 'Swahili (Kenya)'),
       ( 'Swahili (Tanzania)'),
       ( 'Tamil (India)'),
       ( 'Telugu (India)'),
       ( 'Thai (Thailand)'),
       ( 'Turkish (Turkey)'),
       ( 'Ukrainian (Ukraine)'),
       ( 'Uzbek (Uzbekistan)'),
       ( 'Vietnamese (Vietnam)'),
       ( 'Chinese (Mandarin, Simplified)'),
       ( 'Chinese (Southwestern Mandarin, Simplified) Sichuan accent'),
       ( 'Chinese (Cantonese, Traditional)'),
       ( 'Chinese (Taiwanese Mandarin)'),
       ( 'Zulu (South Africa)');