# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - tts-be-app

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://ttsappregistry.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_24b5db3b050f4a5aafaff782708b7daa }}
        password: ${{ secrets.AzureAppService_ContainerPassword_c6bd25be7831409cad82e7e9d4c20cb9 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: ttsappregistry.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_24b5db3b050f4a5aafaff782708b7daa }}/tts-be:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'tts-be-app'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_86cc3bb4b93140149b6a6d0ef491c4f8 }}
        images: 'ttsappregistry.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_24b5db3b050f4a5aafaff782708b7daa }}/tts-be:${{ github.sha }}'